<a href="https://colab.research.google.com/github/cristhian032002/Actividades-seminario/blob/main/1_PPvsSpark_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas vs Polars vs Spark vs Dask
[Author: Elias Buitrago Bolivar](https://github.com/ebuitrago?tab=repositories)

Inspired in: https://www.youtube.com/watch?v=mi9f9zOaqM8

Original data: Kaggle

This jupyter notebook is designed to study and compare different tools to read and manipulate data; to be used in the data undertanding phase. The corresponding explanations will be given directly in class, therefore the material isn't autoexplained. Don´t forget ask me for the access to the data. And, please, give credits to the original author's idea and, if consider, also to me.

_Updated: June 20th, 2023_

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Playing with pandas

In [ ]:
import pandas as pd
#flights_file1 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2018.parquet"
#flights_file2 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2020.parquet"
#flights_file4 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2022.parquet"
#df1 = pd.read_parquet(flights_file1)
#df2 = pd.read_parquet(flights_file2)
df3 = pd.read_parquet(flights_file3)
#df4 = pd.read_parquet(flights_file4)
df5 = pd.read_parquet(flights_file5)

In [ ]:
df = pd.concat([df3, df5])
#df = df2

In [ ]:
 %%timeit

df_agg = df.groupby(['Airline','Year'])[["DepDelayMinutes", "ArrDelayMinutes"]].agg(
    ["mean", "sum", "max"]
)
df_agg = df_agg.reset_index()
df_agg.to_parquet("temp_pandas.parquet")

1.63 s ± 305 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash temp_pandas.parquet

12K -rw-r--r-- 1 root 9.9K Jul  3 00:21 temp_pandas.parquet

In [ ]:
pd.read_parquet('temp_pandas.parquet')

                                      Airline  Year DepDelayMinutes  \
                                                               mean
0                 Air Wisconsin Airlines Corp  2020        8.583725
1                 Air Wisconsin Airlines Corp  2022       13.124801
2                        Alaska Airlines Inc.  2020        5.818328
3                        Alaska Airlines Inc.  2022       10.153994
4                               Allegiant Air  2020       12.825575
5                               Allegiant Air  2022       22.688601
6                      American Airlines Inc.  2020        7.624477
7                      American Airlines Inc.  2022       17.718716
8                 Capital Cargo International  2020        7.665063
9                 Capital Cargo International  2022       12.052814
10                                Comair Inc.  2020       10.068723
11                                Comair Inc.  2022       16.925615
12  Commutair Aka Champlain Enterprises, Inc.  2020       12.266858
13  Commutair Aka Champlain Enterprises, Inc.  2022       16.342795
14                           Compass Airlines  2020        8.215550
15                       Delta Air Lines Inc.  2020        5.581694
16                       Delta Air Lines Inc.  2022       13.842472
17                       Empire Airlines Inc.  2020        6.861561
18                          Endeavor Air Inc.  2020        5.653603
19                          Endeavor Air Inc.  2022       13.284602
20                                  Envoy Air  2020        6.685444
21                                  Envoy Air  2022       10.196954
22                   ExpressJet Airlines Inc.  2020        6.396004
23                     Frontier Airlines Inc.  2020        7.398021
24                     Frontier Airlines Inc.  2022       23.560713
25   GoJet Airlines, LLC d/b/a United Express  2020        8.309550
26   GoJet Airlines, LLC d/b/a United Express  2022       20.259624
27                     Hawaiian Airlines Inc.  2020        3.592000
28                     Hawaiian Airlines Inc.  2022        8.890739
29                                Horizon Air  2020        4.849894
30                                Horizon Air  2022        8.893327
31                            JetBlue Airways  2020        8.213825
32                            JetBlue Airways  2022       29.101873
33                         Mesa Airlines Inc.  2020        9.662425
34                         Mesa Airlines Inc.  2022       18.850643
35                          Republic Airlines  2020        5.224466
36                          Republic Airlines  2022       14.896160
37                      SkyWest Airlines Inc.  2020        8.671988
38                      SkyWest Airlines Inc.  2022       14.964957
39                     Southwest Airlines Co.  2020        4.116316
40                     Southwest Airlines Co.  2022       15.959255
41                           Spirit Air Lines  2020        7.809889
42                           Spirit Air Lines  2022       18.395281
43                      Trans States Airlines  2020       13.739364
44                      United Air Lines Inc.  2020        6.925499
45                      United Air Lines Inc.  2022       16.390842

                       ArrDelayMinutes
           sum     max            mean        sum     max
0     433315.0  1460.0        8.982529   452450.0  1439.0
1     510581.0  1355.0       13.340409   517261.0  1353.0
2     772930.0   823.0        6.365082   843157.0   788.0
3    1278134.0   915.0       11.026280  1382905.0   908.0
4    1080016.0  1648.0       13.331111  1115734.0  1645.0
5    1602632.0  1917.0       25.350068  1785963.0  1919.0
6    4084097.0  3890.0        7.861155  4202644.0  3864.0
7    8464195.0  2994.0       17.860139  8499122.0  2977.0
8     512969.0  1482.0        8.427212   561522.0  1470.0
9     619599.0  1512.0       13.050802   667418.0  1490.0
10   1798294.0  1919.0       10.686808  1903235.0  1888.0
11   2212601.0  1607.0       17.623038  2293374.0  1612.0
12    385670.0  1557.0       13.438158   421340.0  1555.0
13    700730.0  1464.0       17.008007   726497.0  1456.0
14    120670.0  1431.0        8.641498   126693.0  1412.0
15   3083283.0  1195.0        6.209070  3424414.0  1193.0
16   6948367.0  1287.0       13.111550  6565084.0  1285.0
17     32613.0   274.0        7.028136    33222.0   272.0
18   1156405.0  2579.0        5.877866  1200707.0  2560.0
19   1819220.0  1973.0       14.184149  1935952.0  1968.0
20   1339382.0  2248.0        8.417206  1682490.0  2238.0
21   1498942.0  5327.0       10.942435  1603023.0  5324.0
22    308249.0  1357.0        7.443095   357797.0  1338.0
23    640062.0   645.0        7.330406   633479.0   638.0
24   1982257.0  1288.0       23.980928  2011856.0  1311.0
25    304786.0  1408.0        8.336411   305196.0  1382.0
26    656817.0  1220.0       21.749690   702254.0  1199.0
27    137491.0  1484.0        4.092661   156487.0  1481.0
28    372193.0  1847.0        9.069343   379289.0  1805.0
29    445133.0   775.0        5.351232   489932.0   758.0
30    492717.0   803.0        9.589591   529729.0   803.0
31   1118838.0  1135.0        8.503231  1155334.0  1153.0
32   4346161.0  2052.0       28.378086  4214912.0  2029.0
33   1236887.0  1890.0       10.344427  1320704.0  1884.0
34   1301750.0  1837.0       18.298697  1260030.0  1818.0
35   1093533.0  1352.0        5.824160  1216865.0  1381.0
36   2782424.0  7223.0       16.470389  3060890.0  7232.0
37   4963057.0  2327.0        8.718970  4976457.0  2308.0
38   6460357.0  2366.0       15.138498  6514262.0  2363.0
39   3637115.0   602.0        3.372148  2975631.0   597.0
40  11393105.0   747.0       13.865528  9875667.0   731.0
41   1032194.0  1339.0        7.758486  1023290.0  1262.0
42   2301452.0  1436.0       19.172122  2391914.0  1436.0
43    235108.0  1390.0       14.784864   252008.0  1366.0
44   1978518.0  1471.0        6.766355  1929514.0  1503.0
45   5640056.0  1520.0       15.587743  5345489.0  1496.0

In [ ]:
pd.read_parquet('temp_pandas.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   (Airline, )              46 non-null     object
 1   (Year, )                 46 non-null     int64
 2   (DepDelayMinutes, mean)  46 non-null     float64
 3   (DepDelayMinutes, sum)   46 non-null     float64
 4   (DepDelayMinutes, max)   46 non-null     float64
 5   (ArrDelayMinutes, mean)  46 non-null     float64
 6   (ArrDelayMinutes, sum)   46 non-null     float64
 7   (ArrDelayMinutes, max)   46 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 3.0+ KB

## Playing with Polars

In [ ]:
import polars as pl

In [ ]:
flights_file1 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2020.parquet"
flights_file4 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2022.parquet"
df1 = pl.scan_parquet(flights_file1)
df2 = pl.scan_parquet(flights_file2)
df3 = pl.scan_parquet(flights_file3)
df4 = pl.scan_parquet(flights_file4)
df5 = pl.scan_parquet(flights_file5)

In [ ]:
 %%timeit

df_polars = (
    pl.concat([df1, df2, df3, df4, df5])
    .groupby(['Airline', 'Year'])
    .agg([
        pl.col("DepDelayMinutes").mean().alias("avg_dep_delay"),
        pl.col("DepDelayMinutes").sum().alias("sum_dep_delay"),
        pl.col("DepDelayMinutes").max().alias("max_dep_delay"),
        pl.col("ArrDelayMinutes").mean().alias("avg_arr_delay"),
        pl.col("ArrDelayMinutes").sum().alias("sum_arr_delay"),
        pl.col("ArrDelayMinutes").max().alias("max_arr_delay"),
      ])
).collect()

df_polars.write_parquet('temp_polars.parquet')

<magic-timeit>:3: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.

10.2 s ± 1.13 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash temp_polars.parquet

12K -rw-r--r-- 1 root 8.1K Jul  3 00:29 temp_polars.parquet

## Playing with PySpark

In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=fd98ad8100676efc67a09287a670ac51c2f2c80b660dd6952a047686af131c9e
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, max, sum, concat

In [ ]:
spark = SparkSession.builder.master("local[1]").appName("airline-example").getOrCreate()

In [ ]:
flights_file1 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2020.parquet"
flights_file4 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2022.parquet"

In [ ]:
df_spark1 = spark.read.parquet(flights_file1)
df_spark2 = spark.read.parquet(flights_file2)
df_spark3 = spark.read.parquet(flights_file3)
df_spark4 = spark.read.parquet(flights_file4)
df_spark5 = spark.read.parquet(flights_file5)

In [ ]:
df_spark = df_spark1.union(df_spark2)
df_spark = df_spark.union(df_spark3)
df_spark = df_spark.union(df_spark4)
df_spark = df_spark.union(df_spark5)

In [ ]:
 %%timeit

df_spark_agg = df_spark.groupby("Airline", "Year").agg(
    avg("ArrDelayMinutes").alias('avg_arr_delay'),
    sum("ArrDelayMinutes").alias('sum_arr_delay'),
    max("ArrDelayMinutes").alias('max_arr_delay'),
    avg("DepDelayMinutes").alias('avg_dep_delay'),
    sum("DepDelayMinutes").alias('sum_dep_delay'),
    max("DepDelayMinutes").alias('max_dep_delay'),
)
df_spark_agg.write.mode('overwrite').parquet('temp_spark.parquet')

9.79 s ± 716 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash temp_pyspark.parquet

ls: cannot access 'temp_pyspark.parquet': No such file or directory

## Playing with dask

In [ ]:
import pandas as pd
import dask.dataframe as dd
flights_file1 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2020.parquet"
flights_file4 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SEMINARIO/ACTIVIDAD1/Combined_Flights_2022.parquet"
df1 = dd.read_parquet(flights_file1)
df2 = dd.read_parquet(flights_file2)
df3 = dd.read_parquet(flights_file3)
df4 = dd.read_parquet(flights_file4)
df5 = dd.read_parquet(flights_file5)

In [ ]:
df = dd.concat([df3, df5])

In [ ]:
print(df.compute())

       FlightDate            Airline Origin Dest  Cancelled  Diverted  \
0      2020-09-01        Comair Inc.    PHL  DAY      False     False
1      2020-09-02        Comair Inc.    PHL  DAY      False     False
2      2020-09-03        Comair Inc.    PHL  DAY      False     False
3      2020-09-04        Comair Inc.    PHL  DAY      False     False
4      2020-09-05        Comair Inc.    PHL  DAY      False     False
...           ...                ...    ...  ...        ...       ...
590537 2022-03-31  Republic Airlines    MSY  EWR      False      True
590538 2022-03-17  Republic Airlines    CLT  EWR       True     False
590539 2022-03-08  Republic Airlines    ALB  ORD      False     False
590540 2022-03-25  Republic Airlines    EWR  PIT      False      True
590541 2022-03-07  Republic Airlines    EWR  RDU      False      True

        CRSDepTime  DepTime  DepDelayMinutes  DepDelay  ...  WheelsOff  \
0             1905   1858.0              0.0      -7.0  ...     1914.0
1             1905   1858.0              0.0      -7.0  ...     1914.0
2             1905   1855.0              0.0     -10.0  ...     2000.0
3             1905   1857.0              0.0      -8.0  ...     1910.0
4             1905   1856.0              0.0      -9.0  ...     1910.0
...            ...      ...              ...       ...  ...        ...
590537        1949   2014.0             25.0      25.0  ...     2031.0
590538        1733   1817.0             44.0      44.0  ...        NaN
590539        1700   2318.0            378.0     378.0  ...     2337.0
590540        2129   2322.0            113.0     113.0  ...     2347.0
590541        1154   1148.0              0.0      -6.0  ...     1201.0

        WheelsOn  TaxiIn  CRSArrTime  ArrDelay  ArrDel15  ArrivalDelayGroups  \
0         2030.0     4.0        2056     -22.0       0.0                -2.0
1         2022.0     5.0        2056     -29.0       0.0                -2.0
2         2117.0     5.0        2056      26.0       1.0                 1.0
3         2023.0     4.0        2056     -29.0       0.0                -2.0
4         2022.0     4.0        2056     -30.0       0.0                -2.0
...          ...     ...         ...       ...       ...                 ...
590537     202.0    32.0        2354       NaN       NaN                 NaN
590538       NaN     NaN        1942       NaN       NaN                 NaN
590539      52.0     7.0        1838     381.0       1.0                12.0
590540     933.0     6.0        2255       NaN       NaN                 NaN
590541    1552.0     4.0        1333       NaN       NaN                 NaN

        ArrTimeBlk  DistanceGroup  DivAirportLandings
0        2000-2059              2                 0.0
1        2000-2059              2                 0.0
2        2000-2059              2                 0.0
3        2000-2059              2                 0.0
4        2000-2059              2                 0.0
...            ...            ...                 ...
590537   2300-2359              5                 1.0
590538   1900-1959              3                 0.0
590539   1800-1859              3                 0.0
590540   2200-2259              2                 1.0
590541   1300-1359              2                 1.0

[9100715 rows x 61 columns]

In [ ]:
df = df.compute()

In [ ]:
# %%timeit

df_agg = df.groupby(['Airline','Year'])[["DepDelayMinutes", "ArrDelayMinutes"]].agg(
    ["mean", "sum", "max"]
)
df_agg = df_agg.reset_index()
df_agg.to_parquet("temp_dask.parquet")

In [ ]:
!ls -GFlash temp_pandas.parquet

ls: cannot access 'temp_pandas.parquet': No such file or directory

In [ ]:
pd.read_parquet('temp_dask.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   (Airline, )              46 non-null     string
 1   (Year, )                 46 non-null     int64
 2   (DepDelayMinutes, mean)  46 non-null     float64
 3   (DepDelayMinutes, sum)   46 non-null     float64
 4   (DepDelayMinutes, max)   46 non-null     float64
 5   (ArrDelayMinutes, mean)  46 non-null     float64
 6   (ArrDelayMinutes, sum)   46 non-null     float64
 7   (ArrDelayMinutes, max)   46 non-null     float64
dtypes: float64(6), int64(1), string(1)
memory usage: 3.0 KB

In [ ]:
pd.read_parquet('temp_dask.parquet')

                                      Airline  Year DepDelayMinutes  \
                                                               mean
0                 Air Wisconsin Airlines Corp  2020        8.583725
1                 Air Wisconsin Airlines Corp  2022       13.124801
2                        Alaska Airlines Inc.  2020        5.818328
3                        Alaska Airlines Inc.  2022       10.153994
4                               Allegiant Air  2020       12.825575
5                               Allegiant Air  2022       22.688601
6                      American Airlines Inc.  2020        7.624477
7                      American Airlines Inc.  2022       17.718716
8                 Capital Cargo International  2020        7.665063
9                 Capital Cargo International  2022       12.052814
10                                Comair Inc.  2020       10.068723
11                                Comair Inc.  2022       16.925615
12  Commutair Aka Champlain Enterprises, Inc.  2020       12.266858
13  Commutair Aka Champlain Enterprises, Inc.  2022       16.342795
14                           Compass Airlines  2020        8.215550
15                       Delta Air Lines Inc.  2020        5.581694
16                       Delta Air Lines Inc.  2022       13.842472
17                       Empire Airlines Inc.  2020        6.861561
18                          Endeavor Air Inc.  2020        5.653603
19                          Endeavor Air Inc.  2022       13.284602
20                                  Envoy Air  2020        6.685444
21                                  Envoy Air  2022       10.196954
22                   ExpressJet Airlines Inc.  2020        6.396004
23                     Frontier Airlines Inc.  2020        7.398021
24                     Frontier Airlines Inc.  2022       23.560713
25   GoJet Airlines, LLC d/b/a United Express  2020        8.309550
26   GoJet Airlines, LLC d/b/a United Express  2022       20.259624
27                     Hawaiian Airlines Inc.  2020        3.592000
28                     Hawaiian Airlines Inc.  2022        8.890739
29                                Horizon Air  2020        4.849894
30                                Horizon Air  2022        8.893327
31                            JetBlue Airways  2020        8.213825
32                            JetBlue Airways  2022       29.101873
33                         Mesa Airlines Inc.  2020        9.662425
34                         Mesa Airlines Inc.  2022       18.850643
35                          Republic Airlines  2020        5.224466
36                          Republic Airlines  2022       14.896160
37                      SkyWest Airlines Inc.  2020        8.671988
38                      SkyWest Airlines Inc.  2022       14.964957
39                     Southwest Airlines Co.  2020        4.116316
40                     Southwest Airlines Co.  2022       15.959255
41                           Spirit Air Lines  2020        7.809889
42                           Spirit Air Lines  2022       18.395281
43                      Trans States Airlines  2020       13.739364
44                      United Air Lines Inc.  2020        6.925499
45                      United Air Lines Inc.  2022       16.390842

                       ArrDelayMinutes
           sum     max            mean        sum     max
0     433315.0  1460.0        8.982529   452450.0  1439.0
1     510581.0  1355.0       13.340409   517261.0  1353.0
2     772930.0   823.0        6.365082   843157.0   788.0
3    1278134.0   915.0       11.026280  1382905.0   908.0
4    1080016.0  1648.0       13.331111  1115734.0  1645.0
5    1602632.0  1917.0       25.350068  1785963.0  1919.0
6    4084097.0  3890.0        7.861155  4202644.0  3864.0
7    8464195.0  2994.0       17.860139  8499122.0  2977.0
8     512969.0  1482.0        8.427212   561522.0  1470.0
9     619599.0  1512.0       13.050802   667418.0  1490.0
10   1798294.0  1919.0       10.686808  1903235.0  1888.0
11   2212601.0  1607.0       17.623038  2293374.0  1612.0
12    385670.0  1557.0       13.438158   421340.0  1555.0
13    700730.0  1464.0       17.008007   726497.0  1456.0
14    120670.0  1431.0        8.641498   126693.0  1412.0
15   3083283.0  1195.0        6.209070  3424414.0  1193.0
16   6948367.0  1287.0       13.111550  6565084.0  1285.0
17     32613.0   274.0        7.028136    33222.0   272.0
18   1156405.0  2579.0        5.877866  1200707.0  2560.0
19   1819220.0  1973.0       14.184149  1935952.0  1968.0
20   1339382.0  2248.0        8.417206  1682490.0  2238.0
21   1498942.0  5327.0       10.942435  1603023.0  5324.0
22    308249.0  1357.0        7.443095   357797.0  1338.0
23    640062.0   645.0        7.330406   633479.0   638.0
24   1982257.0  1288.0       23.980928  2011856.0  1311.0
25    304786.0  1408.0        8.336411   305196.0  1382.0
26    656817.0  1220.0       21.749690   702254.0  1199.0
27    137491.0  1484.0        4.092661   156487.0  1481.0
28    372193.0  1847.0        9.069343   379289.0  1805.0
29    445133.0   775.0        5.351232   489932.0   758.0
30    492717.0   803.0        9.589591   529729.0   803.0
31   1118838.0  1135.0        8.503231  1155334.0  1153.0
32   4346161.0  2052.0       28.378086  4214912.0  2029.0
33   1236887.0  1890.0       10.344427  1320704.0  1884.0
34   1301750.0  1837.0       18.298697  1260030.0  1818.0
35   1093533.0  1352.0        5.824160  1216865.0  1381.0
36   2782424.0  7223.0       16.470389  3060890.0  7232.0
37   4963057.0  2327.0        8.718970  4976457.0  2308.0
38   6460357.0  2366.0       15.138498  6514262.0  2363.0
39   3637115.0   602.0        3.372148  2975631.0   597.0
40  11393105.0   747.0       13.865528  9875667.0   731.0
41   1032194.0  1339.0        7.758486  1023290.0  1262.0
42   2301452.0  1436.0       19.172122  2391914.0  1436.0
43    235108.0  1390.0       14.784864   252008.0  1366.0
44   1978518.0  1471.0        6.766355  1929514.0  1503.0
45   5640056.0  1520.0       15.587743  5345489.0  1496.0

## Read Results

In [ ]:
import pandas as pd

In [ ]:
agg_pandas = pd.read_parquet('temp_pandas.parquet')
agg_polars = pd.read_parquet('temp_polars.parquet')
agg_spark = pd.read_parquet('temp_spark.parquet')
agg_dask = pd.read_parquet('temp_dask.parquet')

In [ ]:
agg_pandas.shape, agg_polars.shape, agg_spark.shape, agg_dask.shape

((26, 8), (122, 8), (122, 8), (26, 8))

In [ ]:
agg_pandas.sort_values(['Airline','Year']).head()

                       Airline  Year DepDelayMinutes                      \
                                                mean         sum     max
0  Air Wisconsin Airlines Corp  2019       16.868511   1742281.0  1690.0
1         Alaska Airlines Inc.  2019        9.836041   2576246.0  1117.0
2                Allegiant Air  2019       14.678433   1536876.0  1979.0
3       American Airlines Inc.  2019       14.895515  13814816.0  2315.0
4  Capital Cargo International  2019       11.525332   1367642.0  1182.0

  ArrDelayMinutes
             mean         sum     max
0       17.610384   1811545.0  1707.0
1       10.787284   2815643.0  1087.0
2       15.556524   1624770.0  1966.0
3       15.251863  14096412.0  2350.0
4       12.489465   1474806.0  1190.0

In [ ]:
agg_polars.sort_values(['Airline','Year']).head()

,Airline,Year,avg_dep_delay,sum_dep_delay,max_dep_delay,avg_arr_delay,sum_arr_delay,max_arr_delay
28,Air Wisconsin Airlines Corp,2018,16.753459,1606774.0,1296.0,17.881934,1708887.0,1292.0
54,Air Wisconsin Airlines Corp,2019,16.868511,1742281.0,1690.0,17.610384,1811545.0,1707.0
106,Air Wisconsin Airlines Corp,2020,8.583725,433315.0,1460.0,8.982529,452450.0,1439.0
6,Air Wisconsin Airlines Corp,2021,16.553045,1290194.0,1421.0,17.327440,1346602.0,1416.0
67,Air Wisconsin Airlines Corp,2022,13.124801,510581.0,1355.0,13.340409,517261.0,1353.0

In [ ]:
agg_spark.sort_values(['Airline','Year']).head()

,Airline,Year,avg_arr_delay,sum_arr_delay,max_arr_delay,avg_dep_delay,sum_dep_delay,max_dep_delay
0,Air Wisconsin Airlines Corp,2018,17.881934,1708887.0,1292.0,16.753459,1606774.0,1296.0
48,Air Wisconsin Airlines Corp,2019,17.610384,1811545.0,1707.0,16.868511,1742281.0,1690.0
56,Air Wisconsin Airlines Corp,2020,8.982529,452450.0,1439.0,8.583725,433315.0,1460.0
93,Air Wisconsin Airlines Corp,2021,17.327440,1346602.0,1416.0,16.553045,1290194.0,1421.0
119,Air Wisconsin Airlines Corp,2022,13.340409,517261.0,1353.0,13.124801,510581.0,1355.0

In [ ]:
agg_dask.sort_values(['Airline','Year']).head()

                       Airline  Year DepDelayMinutes                      \
                                                mean         sum     max
0  Air Wisconsin Airlines Corp  2019       16.868511   1742281.0  1690.0
1         Alaska Airlines Inc.  2019        9.836041   2576246.0  1117.0
2                Allegiant Air  2019       14.678433   1536876.0  1979.0
3       American Airlines Inc.  2019       14.895515  13814816.0  2315.0
4  Capital Cargo International  2019       11.525332   1367642.0  1182.0

  ArrDelayMinutes
             mean         sum     max
0       17.610384   1811545.0  1707.0
1       10.787284   2815643.0  1087.0
2       15.556524   1624770.0  1966.0
3       15.251863  14096412.0  2350.0
4       12.489465   1474806.0  1190.0